### PR TITLE
Delete items now accepts the type of delete as an optional parameter

### PR DESCRIPTION
**Pull request by RobertPlant**
Delete items can now be passed an optional delete item type, defaults to what it currently is

### CODE REVIEW

**Comment by Garethp** [comment]
So, a couple of notes. Is there a reason why this is a better option than `$api->deleteItems($items, [ 'DeleteType' => DisposalType::MOVE_TO_DELETED_ITEMS ]);`? I'm trying to figure out the why behind having this.

The other comment is that I'd like to keep the `$options = []` parameter as the last parameter for every function. As you can, it's basically a manual override for any default options, or to add things. So if I were to merge it in, I'd likely want `$deleteType` to come *before* `$options`, but the idea of doing `$api->deleteItems($items, default, $options);` to override requests doesn't seem too appealing either...

**Comment by RobertPlant** [comment]
Good point, I did not notice that I could overwrite it with that, I've altered the pull request for options to be passed in from the CalendarAPI using the options field

**Comment by Garethp** [comment]
Sorry, one last nit pick. For readability, I like to keep the `array_replace_recursive` separate. Can you change `return $this->deleteItems($itemId, array_merge(array('SendMeetingCancellations' => 'SendToNone'), $options));` to

```php
$defaultOptions = array (
    'SendMeetingCancellations' => 'SendToNone'
);

$options = array_replace_recursive($defualtOptions, $options);
return $this->deleteItems($itemId, $options);
```

**Comment by Garethp** [comment]
Sorry for being difficult. Thanks a lot for contributing :)

**Comment by RobertPlant** [comment]
No problem, glad to be of assistance.

**Pull request merged**
